export { default as About } from './About';
export { default as Cart } from './Cart';
export { default as Landing } from './Landing';
export { default as Login } from './Login';
export { default as Orders } from './Orders';
export { default as Products } from './Products';
export { default as Register } from './Register';
export { default as SingleProduct } from './SingleProduct';
export { default as HomeLayout } from './HomeLayout';
export { default as Error } from './Error';
export { default as Checkout } from './Checkout';
export { default as ProductCreate } from './ProductCreate';
export { default as Privacy } from './Privacy'
export { default as DashBoard } from './DashBoard';
export { default as RegisterSeller } from './RegisterSeller'
export { default as SellerProducts } from './SellerProducts'